### ISSUE TITLE
Catch convert errors and warnings

### ISSUE THREAD

**Issue by simeonackermann** [RMLio/yarrrml-parser#102]
### Description
Currently its not possible to catch yarrrml2rml convert errors and warnings. My idea was to simply log these messages and return them if requested. I think its better then throw errors and exit the conversion, because we may want ignore the warnings. 
I don't really know how others solve this issue, but I simply solved it for me with a static logger (based on [js-logger)](https://www.npmjs.com/package/js-logger) on my fork: https://github.com/simeonackermann/yarrrml-parser/tree/feature-logger

Usage is:

```js
const y2r = new yarrrml();
...
if ( y2r.getLogger().has('error') ) {
   const logs = y2r.getLogger().getAll();
   ...
}
```

Shall I open a PR for this?

### Existing features it breaks
nothing

**Comment by bjdmeest** [comment]
That looks great! We just need to verify that this works equally well for CLI and when using it as a library, feel free to open a PR!
