### ISSUE TITLE
Special character escape

### ISSUE THREAD

**Issue by ritamargherita** [RMLio/yarrrml-parser#112]
### Description
The forward slash "/" gets replaced with "%2F" when is found in the URI

### Steps
xml as follow:
`<resource xmlns="http://datacite.org/schema/kernel-4"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.1/metadata.xsd">
   <identifier identifierType="DOI">10.17026/dans-z34-fjds</identifier>
   <creators>
      <creator>
         <creatorName>Stichting Mondelinge Geschiedenis Indonesië (SMGI)</creatorName>
      </creator>
      <creator>
         <creatorName>Koninklijk Instituut voor Taal-, Land- en Volkenkunde (KITLV)</creatorName>
      </creator>
   </creators>
   <titles>
      <title>Interviewcollectie Stichting Mondelinge Geschiedenis Indonesië, interview 1007</title>
   </titles>
   <publisher>Data Archiving and Networked Services (DANS)</publisher>
   <publicationYear>2011</publicationYear>
   <subjects>
      <subject subjectScheme="NARCIS-classification"
               schemeURI="http://www.narcis.nl/classification"
               valueURI="http://www.narcis.nl/classfication/D30000"
               xml:lang="en">Humanities</subject>
      <subject subjectScheme="NARCIS-classification"
               schemeURI="http://www.narcis.nl/classification"
               valueURI="http://www.narcis.nl/classfication/D34000"
               xml:lang="en">History</subject>
      <subject subjectScheme="NARCIS-classification"
               schemeURI="http://www.narcis.nl/classification"
               valueURI="http://www.narcis.nl/classfication/D60000"
               xml:lang="en">Social sciences</subject>
      <subject>dekolonisatie</subject>
      <subject>oral history</subject>
      <subject>koloniale samenleving</subject>
      <subject>Japanse bezetting</subject>
      <subject>Japanse capitulatie</subject>
      <subject>Bersiap</subject>
      <subject>interneringskampen</subject>
      <subject>KNIL</subject>
      <subject>Nederlands Indië</subject>
      <subject>Indonesische onafhankelijkheid</subject>
      <subject>Temporal coverage: 1940-1962</subject>
   </subjects>
   <contributors>
      <contributor contributorType="Other">
         <contributorName>Fridus Steijlen (coördinator)</contributorName>
      </contributor>
   </contributors>
   <fundingReferences/>
   <dates>
      <date dateType="Submitted">2011-09-22</date>
      <date dateType="Created">1997-04-02</date>
      <date dateType="Available">2011-08-24</date>
   </dates>
   <language>nl</language>
   <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
   <alternateIdentifiers>
      <alternateIdentifier alternateIdentifierType="URN">urn:nbn:nl:ui:13-pkmq-tv</alternateIdentifier>
      <alternateIdentifier alternateIdentifierType="DMO_ID">easy-dataset:46951</alternateIdentifier>
   </alternateIdentifiers>
   <relatedIdentifiers/>
   <formats>
      <format>RTF</format>
   </formats>
   <rightsList>
      <rights>info:eu-repo/semantics/restrictedAccess</rights>
      <rights rightsURI="https://dans.knaw.nl/en/about/organisation-and-policy/legal-information/DANSLicence.pdf">DANS License</rights>
   </rightsList>
   <descriptions>
      <description descriptionType="Other">De geïnterviewde kwam na de capitulatie van Japan in kampen terecht. Hierna kwam hij bij het KNIL en diende tot aan de opheffing. De bersiap tijd was verwarrend. Hij vertelt over de omstandigheden in de kampen. De zogenaamde beschermingskampen voelde als gevangenschap. De geïnterviewde wilde Nederlands-Indië behouden. De geïnterviewde vertelt over de soevereiniteitsoverdracht. Hij vertelt over de leefwijze van zijn familie en gaat in op zijn gevoelens bij het onafhankelijk worden van Indonesië. In 1954 ging hij naar Nederland.</description>
   </descriptions>
   <geoLocations>
      <geoLocation>
         <geoLocationPlace>Indonesië</geoLocationPlace>
      </geoLocation>
   </geoLocations>
</resource>`

YARRRML:
`prefixes:
  dans: https://example.org/dansOntology/
  doi: http://doi.org/
  dct: http://purl.org/dc/terms/
  disco: http://rdf-vocabulary.ddialliance.org/discovery#
  opl: http://www.w3id.org/odissei/ns/terms_of_use_representation/
  odrl: http://www.w3.org/ns/odrl/2/
  idlab-fn: http://example.com/idlab/function/

mappings:
  test:
    sources:
      - ['dans.xml~xpath', 'resource']
    s: doi:$(identifier)
    po:
      - [a, disco:LogicalDataSet]
      - [dct:creator, $(creators/creator/creatorName),xsd:string]
      - [dct:title, $(titles/title), xsd:string]
      - [dct:publisher, $(publisher), xsd:string]
      - [dct:subject, $(subjects/subject),xsd:string]
      - [dct:contributor, $(contributors/contributor/contributorName), xsd:string]
      - [dct:dateSubmitted, "$(dates/date[@dateType='Submitted'])", xsd:date]
      - [dct:created, "$(dates/date[@dateType='Created'])", xsd:date]
      - [dct:available, "$(dates/date[@dateType='Available'])", xsd:date]
      - [dct:language, $(language), xsd:language]
      - [dct:type, $(resourceType), xsd:string]
      - [dans:easyAltId, $(alternateIdentifiers/alternateIdentifier), xsd:string]
      - [dct:format, $(formats/format), xsd:string]
      - predicates: opl:hasAccess
        objects: 
            - function: idlab-fn:decide
              parameters:
                - [idlab-fn:str, "$(rightsList/rights[1])"]
                - [idlab-fn:expectedStr, "info:eu-repo/semantics/restrictedAccess"]
                - [idlab-fn:result, opl:Restricted] 
              type: iri
            - function: idlab-fn:decide
              parameters:
                - [idlab-fn:str, "$(rightsList/rights[1])"]
                - [idlab-fn:expectedStr, "info:eu-repo/semantics/openAccess"]
                - [idlab-fn:result, opl:Accessible] 
              type: iri
      - predicates: odrl:hasPolicy
        objects:
            - function: idlab-fn:decide
              parameters:
                - [idlab-fn:str, "$(rightsList/rights[2])"]
                - [idlab-fn:expectedStr, "DANS License"]
                - [idlab-fn:result, "https://dans.knaw.nl/en/about/organisation-and-policy/legal-information/DANSLicence.pdf"]
              type: iri
            - function: idlab-fn:decide
              parameters:
                - [idlab-fn:str, "$(rightsList/rights[2])"]
                - [idlab-fn:expectedStr, "License: http://creativecommons.org/publicdomain/zero/1.0"]
                - [idlab-fn:result, "http://creativecommons.org/publicdomain/zero/1.0"]
              type: iri 
      - [dct:description, $(descriptions/description), xsd:string]
      - [dct:spatial, $(geoLocations/geoLocation/geoLocationPlace), xsd:string]
               `

The result for the URI is:
`<http://doi.org/10.17026%2Fdans-z34-fjds> `
instead of:
`<http://doi.org/10.17026/dans-z34-fjds> `

### Environment
OS

**Comment by bjdmeest** [comment]
Hi Rita,

I'm afraid that's intended behavior, see [template value 2.4 of the R2RML spec](https://www.w3.org/TR/r2rml/#dfn-template-value).
If you want to join strings together without any default processing, you can use the function `grel:array_join`, for an example see https://github.com/RMLio/yarrrml-parser/blob/46398f0650f8e24ae728236f9e21858fc6c67cce/test/function-without-parameters/mapping.yarrrml

Does this work for you?

**Comment by ritamargherita** [comment]
Hi Ben,
yes this works thanks!

**Comment by ritamargherita** [comment]
Hello there,

I am not sure if this issue has been closed already, but I just wanted to let you know that I managed to find a solution doing the following:

s:
function: grel:array_join
parameters:
- [grel:p_array_a, doi:]
- [grel:p_array_a, $(identifier)]


Best,
Margherita


On 31 Mar 2021, at 08:45, Ben De Meester ***@***.******@***.***>> wrote:



Hi Rita,

I'm afraid that's intended behavior, see template value 2.4 of the R2RML spec<https://www.w3.org/TR/r2rml/#dfn-template-value>.
If you want to join strings together without any default processing, you can use the function grel:array_join, for an example see https://github.com/RMLio/yarrrml-parser/blob/46398f0650f8e24ae728236f9e21858fc6c67cce/test/function-without-parameters/mapping.yarrrml

Does this work for you?
