### ISSUE TITLE
following paginated JSON APIs

### ISSUE THREAD

**Issue by JBPressac** [RMLio/yarrrml-parser#156]
### Description
_To be able to follow the pages of a JSON API._

### Why it is useful
_Pagination of JSON APIs seems to be a common practice. For instance, [Datasette](https://datasette.io/), a data publishing tool, has a paginated JSON API as specified in https://docs.datasette.io/en/latest/json_api.html?highlight=pagination#pagination. YARRRML does specify how to follow the pages of a JSON API._

### Existing features it breaks
_Unknown_

### Note 
I am not sure if its a request for the YARRRML specification, yarrrml-parser or rmlmapper.jar

**Comment by DylanVanAssche** [comment]
This is a spec issue, moved to the W3C Community Group for Knowledge Graph construction.

See https://github.com/kg-construct/rml-target-source-spec/issues/8

Closing this issue here.
