### ISSUE TITLE
Non-existing Schema.org property

### ISSUE THREAD

**Issue by wouterbeek** [RMLio/yarrrml-parser#168]
### Description

The tutorial on <https://rml.io/yarrrml/tutorial/getting-started/> uses the non-existing property `schema:lastName`.

### Steps

1. Go to the above linked documentation page.
2. Observe the use of `schema:lastName`.
3. Go to Schema.org and notice that the property is not defined there.

### Environment

Ubuntu LTS + Java 11

**Comment by pheyvaer** [comment]
This is fixed now.
