### ISSUE TITLE
Parser generates [object Object] when using functions with graphs

### ISSUE THREAD

**Issue by amohoste** [RMLio/yarrrml-parser#2]
When I try to use a function for the graph value like in in this file: [mapping.yaml.txt](https://github.com/RMLio/yarrrml-parser/files/2270353/mapping.yaml.txt)

The parser generates 
```
:gm_0 a rr:GraphMap;
    rr:template "[object Object]".
```

Instead of the right RML function syntax. Generated RML file:  [rml.txt](https://github.com/RMLio/yarrrml-parser/files/2270348/rml.txt)

**Comment by bjdmeest** [comment]
Fixed with 63c9c62a4267c618f45de4a539d4eff475715506 , is in release v0.1.1, and updated in Matey :)
