### ISSUE TITLE
prefix 2018-03-07T23 was not found.

### ISSUE THREAD

**Issue by amohoste** [RMLio/yarrrml-parser#3]
When I try to use the mapper with the following template: [mapping.yaml.txt](https://github.com/RMLio/yarrrml-parser/files/2273090/mapping.yaml.txt)

The mapper generates an output saying: `prefix 2018-03-07T23 was not found.`
An rml file is generated, but I think the graph triples are missing.

Data file: [data.json.txt](https://github.com/RMLio/yarrrml-parser/files/2273095/data.json.txt)

Rml output: [rml.txt](https://github.com/RMLio/yarrrml-parser/files/2273101/rml.txt)

Note: when testing, make sure to change data.json.txt into data.json as you can't directly upload json to github apparently

**Comment by amohoste** [comment]
When I change my mapping file to use `- [myfun:valueParameter2, last_update]` instead of `- [myfun:valueParameter2, "2018-03-07T23:27:44+01:00"]` I get the same RML output, but don't get a warning.

**Comment by bjdmeest** [comment]
Well, that's intended behavior :). The parser will try to match any prefix, and a prefix is a piece of text ([well, a bit more complicated than that](https://www.w3.org/TR/sparql11-query/#rPN_PREFIX)) with a colon, which is what you have there :). When it can't find a prefix, it'll warn you, but still continue without replacing the prefix.
The parsed RML doc is correct afaict.

**Comment by amohoste** [comment]
Oh okay. Didn't know that would be the behavior when the string is escaped. Then the issue will be probably be in the rmlmapper-java
