### ISSUE TITLE
Allow multiple input files for the CLI

### ISSUE THREAD

**Issue by pheyvaer** [RMLio/yarrrml-parser#34]
The different files are appended, so it's up to the user to make sure that no duplicate keys are used for rules and prefixes. @bjdmeest What do you think?

**Comment by bjdmeest** [comment]
Shouldn't we then add warnings that duplicate keys for rules and prefixes are found? Just for our own ease of debugging sake ;) Otherwise, sounds more than good to me!

**Comment by pheyvaer** [comment]
Yes good idea!

**Comment by vemonet** [comment]
Would it be possible to support wildcards when providing the files to process? 

To run the yarrrml-parser on all `.yarrr.yml` files in a folder:

```bash
yarrrml-parser -i *.yarrr.yml -o .
```

The output files could be in the folder provided by -o with the extension being changed from `.yarrr.yml` to `.rml.ttl`

Not sure about how the output filenames, maybe introducing a different arg for a template output filename for maximum flexibility
