### ISSUE TITLE
MATEY: ~iri is not generated when value contains spaces

### ISSUE THREAD

**Issue by benjimor** [RMLio/yarrrml-parser#9]
On YARRRML's Matey, with a dataset such as:

```json
{
"country1": "United States", 
"country2": "United_States"
...
}
```
When i try to generate an IRI as an object,
The following works:
```yaml
- ['http://dbpedia.org/ontology/country', http://www.example.org/$(country2)~iri]
```
But this fails:
```yaml
- ['http://dbpedia.org/ontology/country', http://www.example.org/$(country1)~iri]
```
It looks like a problem with space... maybe url encoding?

**Comment by pheyvaer** [comment]
Hi @benjimor,

After a quick test it seems to be related to Matey, because the RMLMapper gives the expected result. @bjdmeest can you have a look?

**Comment by bjdmeest** [comment]
Hi @benjimor , we updated the RMLMapper of Matey, and the problem seems to be resolved.
If this wouldn't be the case, feel free to reopen this issue.

**Comment by benjimor** [comment]
Yes it's working ! Thanks for your quick reply.
