### ISSUE TITLE
Mapping TSV files

### ISSUE THREAD

**Issue by nleguillarme** [RMLio/yarrrml-parser#95]
Hi

I am trying to map a TSV file to RDF using YARRRML and RMLmapper, but I can't manage to make it work when specifying "\t" as the delimiter.

I tried to map a minimal example in Matey, and it seems like the "delimiter" key is not translated into RML.

Here is the content of the .tsv file:

> id    name
> 1    Nicolas

Here is the content of YARRRML file:

> prefixes:
>   ex: "http://example.com/"
> 
> mappings:
>   person:
>     sources:
>       access: source_1.tsv
>       referenceFormulation: csv
>       delimiter: \t
>     s: http://example.com/$(id)
>     po:
>       - [a, foaf:Person]
>       - [ex:name, $(name)]

And here is the interesting part of the resulting RML file :

> map:source_0 a rml:LogicalSource;
>     rml:source "source_1.tsv";
>     rml:referenceFormulation ql:CSV.

As you can see, the value of the delimiter key does not appear.
Am I missing something ?

**Comment by pheyvaer** [comment]
Hi @nleguillarme 

Thanks for the issue! Your YARRRML file is indeed correct and the RML file is indeed missing the delimiter details. We will have a look at it!

**Comment by arxos-twinu** [comment]
Hi, I am having issues with custom delimiters for csv. 

I have the file:
`name;lastName
Alexis;Gamboa`

and the Yarrrml file:
`prefixes:
    ex: "http://example.com/"
    csvw: "http://www.w3.org/ns/csvw#"
mappings:
    person:
        sources:
            access: building.csv
            referenceFormulation: csv
            delimiter: ";"
        s: http://example.com/$(name)
        po:
            - [a, foaf:Person]
            - [ex:name, $(name)]`
Yet it fails to map it, anything I might be missing? 

I see the yarrrml parser has this test case: https://github.com/RMLio/yarrrml-parser/tree/13310a27ab6ceec9ca5a467ca064ddaed7bdae47/test/csv-delimiter/semicolon 

I am testing this exact test on matey, maybe it is running and older version of the parser?
